steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'compile', '-f', 'Dockerfile.compile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hexo-blog', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hexo-blog']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'hexo-blog-service', '--image', 'gcr.io/$PROJECT_ID/hexo-blog', '--region', 'asia-east1', '--platform', 'managed', '--allow-unauthenticated', '--port', '80']