steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'compile', '-f', 'Dockerfile.compile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-project-282358/hexo-blog', '.']